<a href="https://colab.research.google.com/github/YuriCatundaGondim/aulaTecnicasdeProgramacao/blob/main/aula01TecPrograma%C3%A7%C3%A3o1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Crie um array unidimensional com números inteiros distribuídos de maneira aleatória de 1 a 100, e filtre apenas os números maiores ou iguais a 50.

In [42]:
import numpy as np
num = np.random.randint(0, 101, 100)
num[num>=50]

array([ 84,  52,  82,  53,  76,  92,  71,  93,  69,  60,  92,  60,  51,
        79,  76,  76,  82,  62,  81,  56,  70,  71,  77,  52,  60,  97,
        67,  56,  71,  90,  76,  98,  64,  84,  91,  53,  91,  70,  77,
        97, 100,  90,  70,  93,  91,  78,  97,  82,  64,  92,  71,  61,
        77,  96])

Crie um array 1-dimensional (com 100 elementos) com números reais (float) aleatórios, e retorne as seguintes métricas:
média
mediana
desvio padrão
máximo
mínimo
índice do elemento máximo
indice do elemento mínimo

In [80]:
num = np.round((np.random.randn(100)*100), 2)
num_reais  = np.where(num >= 0, num, (num*-1))
print(f'mínimo: {min(num_reais)}')
print(f'máximo: {max(num_reais)}')
print(f'índice do máximo: {num_reais.argmax()}')
print(f'índice do mínimo: {num_reais.argmin()}')
print(f'média: {np.round(num_reais.mean())}')
print(f'desvio padrão: {np.round(num_reais.std(), 2)}')
print(f'mediana: {np.median(num_reais)}')



mínimo: 0.65
máximo: 208.07
índice do máximo: 22
índice do mínimo: 89
média: 78.0
desvio padrão: 54.79
mediana: 66.94


Crie uma array 2-dimensional (10x5) com números reais (float) aleatórios, e retorne as seguintes métricas:
média
mediana
desvio padrão
máximo
mínimo
índice do elemento máximo
indice do elemento mínimo

In [111]:
arr2 = np.random.rand(50)
matriz = arr2.reshape((10, 5))
print(matriz)
print(f"media: {matriz.mean()}")
print(f"mediana: {np.median(matriz)}")
print(f"desvio padrão: {matriz.std()}")
print(f"máximo: {matriz.max()}")
print(f"mínimo: {matriz.min()}")
print(f"indice do max: {matriz.argmax()}")
print(f"indice do min: {matriz.argmin()}")

[[0.31207704 0.42450933 0.79035408 0.08648779 0.38496847]
 [0.74426841 0.43409371 0.29535213 0.01952736 0.29894401]
 [0.22549281 0.74503303 0.96695963 0.88594611 0.70919444]
 [0.87258194 0.10514004 0.28700093 0.57220149 0.14803106]
 [0.48791942 0.5934374  0.85475838 0.91974405 0.80545072]
 [0.85339561 0.40430792 0.01776807 0.29046237 0.36189849]
 [0.09128659 0.29587881 0.67675255 0.82976984 0.71913312]
 [0.58699989 0.65350223 0.26245731 0.95902788 0.67478272]
 [0.01971008 0.92901482 0.25030035 0.75033541 0.27958441]
 [0.23009183 0.29489103 0.83642263 0.70300892 0.43878359]]
media: 0.5075808050003174
mediana: 0.46335150298431843
desvio padrão: 0.28705097086665043
máximo: 0.9669596322299364
mínimo: 0.017768066006470074
indice do max: 12
indice do min: 27


Crie um array 1-dimensional com 100 inteiros aleatórios de 0 a 1000, e substitua cada valor ímpar por -1.

In [ ]:
num = np.random.randint(0, 1001, 100)
num[num %2 != 0] = -1 # mesma coisa que np.where(num %2 == 0, num, -1))
num